services:
  postgres:
    image: postgres:15-alpine
    container_name: simucred-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.0
    container_name: simucred-keycloak
    environment:
      KEYCLOAK_ADMIN: ${KEY_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEY_PASSWORD}
    command: start-dev
    ports:
      - "8081:8080"
    networks:
      - simucred-network

volumes:
  postgres_data:

networks:
  simucred-network: